Group-One-FSF-Project-2/zenGarden

models/users.js

I added the model users table.

Adding users sequelize table.

---

models/plants.js

I added the models plants table.

Adding sequelize plants table.

---

models/seeds.js

I added the models seeds table.

Adding the sequelize seeds table.

---

models/gardenplants.js

Added gardenplants sequelize table to models.

Adding sequelize gardenplants table.

---

views/layouts/main.handlebars

Adding bootstrap form for main handlebars

Adding form.

---

models/Plant.js
models/index.js
models/plotPlant.js
server.js

Adding in DB updates and creating new table

Db updates

---

test/timeTest/addTest.js
test/timeTest/growTest.js
test/timeTest/timeStyle.css

added transition

---

public/login.js
views/layouts/main.handlebars

Added login logic and adjusted a couple of thing on the hbs boostrap form

Added login user logic and added an extra element to hbs form for register purposes

---

public/logout.js
views/layouts/main.handlebars

I added the logout function to public folder and a logout button element to the bootstrap form.

Added logout function and logout button to bootstrap form in main hbs page 

---

seeds/seeds.js

Just removed git merging comments from codebase on seeds js file.

I just removed the merging head comment from the seeds js file.

---

server.js

Adjustment to server.js file for port console log. Crystal deserves credit she found fix. She is awesome.

Adjusted server.js file.

---

models/index.js
seeds/gardenplot-seeds.json
seeds/plotPlant-seeds.json
seeds/seeds.js
server.js

Finally got the models configured and seed data running.

seed data working

---

controllers/api/gardenplotRoutes.js
controllers/api/index.js
controllers/api/plantRoutes.js
models/Gardenplot.js
models/index.js

tested and fixed issues when testing the routes for gardenplots. tests passing

Feature gardenroutes

---

controllers/api/userRoutes.js
models/User.js
server.js

User routes are set up
POST Login
POST Create user
POST Logout
GET all users
GET individual user (still working on this one)

User routes

---

public/css/gardenPlot.css
public/garden/TEMPbuttons.js
public/garden/addPlant/addBush.js
public/garden/addPlant/addTree.js
public/garden/growPlant/growBush.js
public/garden/growPlant/growTree.js
public/garden/misc.js
views/home.handlebars

added fetch call to generate plot from db, plus some minor changes the Date() stuff to work with createdAt

added fetch call to generate plot from db

---

controllers/api/gardenplotRoutes.js
views/layouts/main.handlebars

added back in gardenPlot css

---

models/plotPlant.js
public/garden/addPlant/addBush.js
public/garden/addPlant/addFlower.js
public/garden/addPlant/addTree.js
public/garden/form/form.js
seeds/plant-seeds.json
seeds/plotPlant-seeds.json
views/home.handlebars
views/partials/plantForm.handlebars

updated some modals and routing to get plants to POST

Tree, Bush, and Flowers can POST to the db

---

controllers/api/gardenplotRoutes.js
public/garden/misc.js
views/partials/garden.handlebars
views/partials/plantForm.handlebars

Fetch plot

---

public/css/gardenPlot.css
public/garden/addPlant/addBush.js
public/garden/addPlant/addTree.js
public/garden/growPlant/growBush.js
public/garden/growPlant/growTree.js
public/garden/time.js

added timeCycle

---

public/garden/misc.js
server.js
views/home.handlebars

removed excess unneeded commented out code

---

controllers/homeRoutes.js

reverting auth stuff for testing

---

controllers/api/gardenplotRoutes.js
controllers/homeRoutes.js

reverting last pieces of auth

---

README.md

I created a readme layout for consumption. Feel free to adjust if needed.

Adding a readme layout for the project.

---

controllers/homeRoutes.js

Putting auth back in now that it works.

Route auth
